### ISSUE TITLE
Area sound - Invalid syntax

### ISSUE THREAD

**Issue by ghost** [damocles-minetest/area_effects#3]
Area sound cant be set with `/area_effect_set sound SOUNDNAME`

Returns "Invalid syntax!"

**Comment by BuckarooBanzay** [comment]
> Area sound cant be set with `/area_effect_set sound SOUNDNAME`
> 
> Returns "Invalid syntax!"

Have you tried `/area_effect_set [area_id*] sound SOUNDNAME` ? :wink: 

**EDIT**: i haven't tested that part yet, just fyi...

**Comment by ghost** [comment]
That works :)
